"""Add Phase 4 Analytics, Sources, and Threats

Revision ID: 175353378c3b
Revises: daff42fd65ab
Create Date: 2026-03-16 22:21:08.149807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175353378c3b'
down_revision: Union[str, Sequence[str], None] = 'daff42fd65ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
