"""Add Phase 4 Analytics, Sources, and Threats Migration 2

Revision ID: b8a0953ea010
Revises: 175353378c3b
Create Date: 2026-03-16 22:21:40.369310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a0953ea010'
down_revision: Union[str, Sequence[str], None] = '175353378c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_id'), 'agent_logs', ['id'], unique=False)
    op.create_table('agent_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('search_queries_used', sa.JSON(), nullable=True),
    sa.Column('research_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_id'), 'agent_memory', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memory_topic'), 'agent_memory', ['topic'], unique=True)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('page_url', sa.String(length=255), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_id'), 'analytics_events', ['id'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_id'), 'research_sources', ['id'], unique=False)
    op.create_table('threat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('malware_name', sa.String(length=255), nullable=False),
    sa.Column('malware_family', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('attack_vector', sa.Text(), nullable=True),
    sa.Column('technical_analysis', sa.Text(), nullable=True),
    sa.Column('command_and_control', sa.Text(), nullable=True),
    sa.Column('indicators_of_compromise', sa.JSON(), nullable=True),
    sa.Column('mitigation_steps', sa.Text(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_reports_id'), 'threat_reports', ['id'], unique=False)
    op.create_index(op.f('ix_threat_reports_malware_name'), 'threat_reports', ['malware_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_reports_malware_name'), table_name='threat_reports')
    op.drop_index(op.f('ix_threat_reports_id'), table_name='threat_reports')
    op.drop_table('threat_reports')
    op.drop_index(op.f('ix_research_sources_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_analytics_events_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_agent_memory_topic'), table_name='agent_memory')
    op.drop_index(op.f('ix_agent_memory_id'), table_name='agent_memory')
    op.drop_table('agent_memory')
    op.drop_index(op.f('ix_agent_logs_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
