"""Add AgentMemory and AgentLogs models

Revision ID: daff42fd65ab
Revises: 24e4f6adc65d
Create Date: 2026-03-16 22:05:50.138557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daff42fd65ab'
down_revision: Union[str, Sequence[str], None] = '24e4f6adc65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
